variable "name" {}
variable "additional_tags" {}
variable "eks_master_role" {}
variable "cluster_version" {}
variable "cluster_name" {}
variable "india_dev_private_subnets" {}
variable "cluster_service_ipv4_cidr" {}
variable "eks_nodegroup_role" {}
variable "eks_cluster_sg" {}
variable "node_group_sg" {}
variable "max_size" {}
variable "min_size" {}
variable "desired_size" {}
variable "disk_size" {}
variable "instance_types" {}
variable "AmazonEKSClusterPolicy" {}
variable "eks_AmazonEKSVPCResourceController" {}
variable "eks_AmazonEKSWorkerNodePolicy" {}
variable "eks_AmazonEKS_CNI_Policy" {}
variable "eks_AmazonEC2ContainerRegistryRindiadOnly" {}